### PR TITLE
t83-adminPage-editWindow

### PR DESCRIPTION
**Pull request by BirhanBey**
edit window added

### CODE REVIEW

**Comment by BirhanBey** [comment]
[Admin page Edit window](https://trello.com/c/BgSbC0Lj/83-admin-page-edit-window)

**Comment by CCornez** [comment]
could you resolve the conflict ?

**Review by CCornez — APPROVED** [review]
nice :)

**Comment by CCornez** [comment]
[Admin page Edit window](https://trello.com/c/BgSbC0Lj/83-admin-page-edit-window)

**Pull request merged**
