### PR TITLE
T39 fun filter

### PR DESCRIPTION
**Pull request by CCornez**
made filter handler && fix .product-main width to 100% at start :)

### CODE REVIEW

**Comment by CCornez** [comment]
i pulled from t40 so I think you need to merge t40 (pull request #7) before this, not sure though

**Comment by CCornez** [comment]
[handle filter](https://trello.com/c/fw6aAbsF/39-handle-filter)

**Comment by CCornez** [comment]
[Fix card appear to far right on first reload](https://trello.com/c/sYZE8zOY/55-fix-card-appear-to-far-right-on-first-reload)

**Comment by BirhanBey** [comment]
nice job man and thanks for the quick solution about the "%100 problem".

**Pull request merged**
