### PR TITLE
T104 active add product

### PR DESCRIPTION
**Pull request by CCornez**

### CODE REVIEW

**Comment by CCornez** [comment]
[add product active not moving](https://trello.com/c/yc0JQut4/104-add-product-active-not-moving)

**Comment by CCornez** [comment]
[add product active not moving](https://trello.com/c/yc0JQut4/104-add-product-active-not-moving)

**Comment by CCornez** [comment]
[add product active not moving](https://trello.com/c/yc0JQut4/104-add-product-active-not-moving)

**Review by BirhanBey — APPROVED** [review]
looks great 👍

**Pull request merged**
